// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStatus():Promise<main.Status>;

export function Run(arg1:string,arg2:boolean):Promise<string>;
